services:
  cms-app:
    image: node:16-buster
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    working_dir: /app
    volumes:
      - ./cms-app/src:/app/src
      - ./cms-app/public:/app/public
      - ./cms-app/_docs:/app/_docs
      - ./cms-app/next.config.js:/app/next.config.js
      - ./cms-app/package.json:/app/package.json
      - ./cms-app/package-lock.json:/app/package-lock.json
      - ./cms-app/dev.sh:/app/dev.sh
    restart: always
    ports:
      - 3001:3000
    command: bash -c "./dev.sh"
    labels:
      - 'traefik.http.routers.cms_app.rule=Host(`test.docker.localhost`) && PathPrefix(`/cms`)'
      - 'traefik.http.services.cms_app.loadbalancer.server.port=3000'

  api:
    restart: always
    user: 1000:1000
    image: node:16-bullseye
    # build:
    #   context: ./truthy
    #   dockerfile: dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./truthy:/usr/src/app
    ports:
      - 7777:7777
    env_file:
      - ./truthy/.env
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    labels:
      - 'traefik.http.routers.api.rule=Host(`test.docker.localhost`) && PathPrefix(`/api`)'
      - 'traefik.http.services.api.loadbalancer.server.port=7777'

  pgweb:
    restart: always
    image: sosedoff/pgweb
    links:
      - postgres:postgres # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://postgres:Aa1234567@postgres:5432/truthy?sslmode=disable
    ports:
      - '8081:8081'
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:12
    env_file:
      - ./truthy/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa1234567
      POSTGRES_DB: truthy
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: '256m'

  redis:
    image: 'redis:alpine'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - 'traefik.http.routers.whoami.rule=Host(`test.docker.localhost`) && PathPrefix(`/whoami`)'

  # proxy:
  #   build:
  #     context: ./reverse-proxy/dev
  #     dockerfile: dockerfile
  #   restart: always
  #   ports:
  #     - 81:81
  #   depends_on:
  #     - cms-app
  #     - api
  matomo:
    image: matomo:4
    ports:
      - 8091:80
      - 8092:443
    volumes:
      - ./volumes/matomo/config:/var/www/html/config:rw
      - ./volumes/matomo/logs:/var/www/html/logs
      # - matomo:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_USERNAME: root
      MATOMO_DATABASE_PASSWORD: password
      MATOMO_DATABASE_DBNAME: matomo_db
    depends_on:
      - mysql
    restart: unless-stopped
    labels:
      - 'traefik.http.routers.matomo.rule=Host(`matomo.test.docker.localhost`) '

  mysql:
    image: mysql:8.0.29
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql-mode=""
    environment:
      MYSQL_DATABASE: tests
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/home/shared
      - ./volumes/mysql:/var/lib/mysql
    restart: unless-stopped

  teedy:
    image: sismics/docs:latest
    # container_name: teedy
    # hostname: teedy
    # restart: unless-stopped
    volumes:
      # - /mnt/sdb1/teedy/teedy_docs:/docs
      - ./volumes/teedy_docs:/docs
    environment:
      - DOCS_BASE_URL=https://docu_share.test.docker.localhost
      - DATABSASE_URL=postgresql://teedy_db:5432/teedy
      - DATABASE_USER=teedy
      - DATABASE_PASSWORD=changeme
      - DOCS_ADMIN_PASSWORD_INIT=$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS

    ports:
      - 8095:8080
    labels:
      # Traefik Labels
      - 'traefik.enable=true'
      # HTTPS Labels
      - 'traefik.http.routers.teedy.rule=Host(`docu_share.test.docker.localhost`)' # Domain Name
      - 'traefik.http.services.teedy.loadbalancer.server.port=8080'

    #   - 'traefik.http.routers.teedy.entrypoints=web-secure'
    #   - 'traefik.http.routers.teedy.middlewares=default-headers@file'
    #   - 'traefik.http.routers.teedy.service=teedy'
    #   - 'traefik.http.routers.teedy.tls=true'
    #   - 'traefik.http.services.teedy.loadbalancer.server.port=8080' # Proxied Port

  teedy_db:
    image: postgres:latest
    # container_name: postgres
    # hostname: postgres
    # restart: unless-stopped
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=teedy
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=teedy

volumes:
  pgdata:
  redisdata:

networks:
  default:
    external:
      name: traefik-proxy-network
