services:
  next-dev:
    image: node:16-buster
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    working_dir: /app
    volumes:
      - .:/app
    restart: always
    ports:
      - 3001:3000
    command: bash -c "./dev.sh"
