@API_HOST=localhost:7777

###
GET http://{{API_HOST}}/api/helloworld-rest-crud

###
GET http://{{API_HOST}}/api/helloworld-rest-crud/44


###
GET http://{{API_HOST}}/api/helloworld-rest-crud/not_found

###
POST http://{{API_HOST}}/api/helloworld-rest-crud
Content-Type: application/json

{
  "firstName": "aaaaaa",
  "lastName": "bbbbbb",
  "isActive": true,
  "tags":[{"id":1}]
}

###
PATCH http://{{API_HOST}}/api/helloworld-rest-crud/44
Content-Type: application/json

{
  "name":"111111",
  "description":"222222",
  "isActive":true
}

###
DELETE http://{{API_HOST}}/api/helloworld-rest-crud/45


# restaurant

###
GET http://{{API_HOST}}/api/helloworld-rest-crud/1


###
POST http://{{API_HOST}}/api/helloworld-rest-crud/delete_all
Content-Type: application/json

{}
