@PORT=7777
@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJodHRwOi8vbG9jYWxob3N0Ojc3NzciLCJhdWRpZW5jZSI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsInN1YmplY3QiOiIxIiwiaXNUd29GQUF1dGhlbnRpY2F0ZWQiOmZhbHNlLCJpYXQiOjE2NTkwMTQ0OTEsImV4cCI6MTY1OTAxNTM5MX0.m6szcrWRYAsedg4NwdsALxvr2fG328RFN9QdTASQbAo
@BASEURL=api

###
GET http://localhost:{{PORT}}/{{BASEURL}}

###
POST http://localhost:{{PORT}}/{{BASEURL}}/auth/login
content-type: application/json

{
  "username": "user1@truthy.com",
  "password": "Truthy@123",
  "remember":true
}

###
POST http://localhost/{{{{BASEURL}}}}/auth/login
content-type: application/json

{
  "username": "user1@truthy.com",
  "password": "Truthy@123",
  "remember":true
}

###
POST http://localhost:{{PORT}}/logout
content-type: application/json

{}

###
GET http://localhost:{{PORT}}/auth/token-info
Authorization: Bearer {{JWT}}

###
DELETE http://localhost:{{PORT}}/users/18
Authorization: Bearer {{JWT}}

###
GET http://localhost:{{PORT}}/users
Authorization: Bearer {{JWT}}

###
PUT http://localhost:{{PORT}}/users/4
Authorization: Bearer {{JWT}}
content-type: application/json

{
  "name": "Maximo69",
  "phone": null,
  "state": "Nebraska",
  "country": "Greenland",
  "address": "44503 Schamberger Islands",
  "address1": "079 Jacobs Center",
  "address2": "9378 Schowalter Unions",
  "contact": null,
  "avatar": null,
  "status": "active",
  "hasDiscount":true,
  "isTwoFAEnabled": false,
  "isVerified": true,
  "contact_info_public": true,
  "available_to_hire": true
}

###
GET http://localhost:{{PORT}}/users?limit=99
Authorization: Bearer {{JWT}}

###
GET http://localhost/api/users
Authorization: Bearer {{JWT}}

###
GET http://localhost/api/auth/profile
Authorization: Bearer {{JWT}}

###
PUT http://localhost/api/auth/profile
Authorization: Bearer {{JWT}}
content-type: application/json

{
  "name": "test_new_name"
}
