FROM node:16-buster

WORKDIR /app

COPY . .

RUN yarn install
RUN yarn build

CMD ["yarn","serve","-s","build"]

# FROM nginx:1.21-alpine
# COPY nginx.conf /etc/nginx/nginx.conf

# FROM nginx
# COPY --from=build-deps /app/build /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# CMD ["nginx", "-g", "daemon off;"]
